version: 2

sphinx:
  configuration: doc/conf.py

python:
    install:
        - requirements: requirements-ci.txt
        - requirements: doc/requirements.txt
        - method: pip
          path: .
    system_packages: true

build:
    os: ubuntu-22.04
    tools:
        python: "3.8"
    jobs:
        pre_install:
            - echo "setuptools~=66.0\npip~=22.0" >> requirements-ci.txt
