name: Manually Triggered Version Bumps

on:
  workflow_dispatch:
  push:

jobs:
  pre_release_version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository and Run pre-release version bump
        uses: actions/checkout@v2
        - uses: PennyLaneAI/automation@v0.3
        - uses: ./version_bump_action
          with:
            version_path: "./pennylane_sf/_version.py"
            changelog_path: "./.github/CHANGELOG.md"
            release_status: "pre_release"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: pre release version bump
          title: Version Bump
          body: updated changelog and _version.py
          branch: pre-release-version-bump
          reviewers: Jaybsoni
          base: master
